Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "rockylinux/9"
    node1.vm.network "private_network", ip: "192.168.33.51"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    node1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
      # ansible.inventory_path = "inventory.ini"
    end
  end
end