Vagrant.configure("2") do |config|

  config.vm.define "node1" do |node1|
    node1.vm.box = "rockylinux/9"
    node1.vm.network "private_network", ip: "192.168.33.61"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    
  # VM resources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 1
  end
  
    node1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
      # ansible.inventory_path = "inventory.ini"
    end
  end
end

